version: '3'

services:
  # Service for calculating heatwaves and coldwaves
  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./extracted_data:/app/extracted_data
      - ./:/app/output
    command: ["--mode", "both"]
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - weather-network

  # Service for the REST API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    volumes:
      - ./:/app/output
      - ./extracted_data:/app/extracted_data
    depends_on:
      - calculator
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge